#!/bin/bash
# =======================================================================
# JIT SSH Agent — Install Script
# =======================================================================
# Usage:
#   curl -fsSL http://YOUR_BACKEND_IP/install.sh | sudo bash
# Or download and run locally:
#   chmod +x install.sh
#   sudo ./install.sh --control-plane http://10.0.1.50:8080/api/v1 \
#                     --tags environment=production,team=devops
# =======================================================================
set -e

INSTALL_DIR="/opt/jit-agent"
CONFIG_DIR="/etc/jit-agent"
BIN_PATH="/usr/local/bin/jit-agent"
SERVICE_FILE="/etc/systemd/system/jit-agent.service"
CONFIG_FILE="$CONFIG_DIR/jit-agent.conf"
LOG_FILE="/var/log/jit-agent.log"

# ------- Defaults -------
CONTROL_PLANE_URL=""
AGENT_TOKEN=""
TAGS="environment=production"
HEARTBEAT_INTERVAL=30
POLL_INTERVAL=15
AGENT_BINARY_URL=""

# ------- Parse arguments -------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --control-plane)
      CONTROL_PLANE_URL="$2"; shift 2 ;;
    --token)
      AGENT_TOKEN="$2"; shift 2 ;;
    --tags)
      TAGS="$2"; shift 2 ;;
    --heartbeat-interval)
      HEARTBEAT_INTERVAL="$2"; shift 2 ;;
    --poll-interval)
      POLL_INTERVAL="$2"; shift 2 ;;
    --binary-url)
      AGENT_BINARY_URL="$2"; shift 2 ;;
    *)
      echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# ------- Validate -------
if [ -z "$CONTROL_PLANE_URL" ]; then
  read -p "Enter JIT Control Plane URL (e.g. http://10.0.1.50:8080/api/v1): " CONTROL_PLANE_URL
fi
if [ -z "$CONTROL_PLANE_URL" ]; then
  echo "ERROR: control_plane_url is required." >&2
  exit 1
fi

echo ""
echo "=== JIT SSH Agent Installer ==="
echo "  Control Plane : $CONTROL_PLANE_URL"
echo "  Token         : ${AGENT_TOKEN:0:4}****${AGENT_TOKEN: -4}"
echo "  Tags          : $TAGS"
echo "  Heartbeat     : ${HEARTBEAT_INTERVAL}s"
echo "  Poll Interval : ${POLL_INTERVAL}s"
echo ""

# ------- Create directories -------
mkdir -p "$CONFIG_DIR" "$INSTALL_DIR"

# ------- Write config file -------
if [ -f "$CONFIG_FILE" ]; then
  echo "[info] Config already exists at $CONFIG_FILE — preserving existing agent_id."
  # Only update the control_plane_url if it changed
  sed -i "s|^control_plane_url.*|control_plane_url = $CONTROL_PLANE_URL|" "$CONFIG_FILE"
  if [ -n "$AGENT_TOKEN" ]; then
    sed -i "s|^agent_token.*|agent_token = $AGENT_TOKEN|" "$CONFIG_FILE"
  fi
  sed -i "s|^tags.*|tags = $TAGS|" "$CONFIG_FILE"
  sed -i "s|^heartbeat_interval_sec.*|heartbeat_interval_sec = $HEARTBEAT_INTERVAL|" "$CONFIG_FILE"
  sed -i "s|^poll_interval_sec.*|poll_interval_sec = $POLL_INTERVAL|" "$CONFIG_FILE"
else
  cat > "$CONFIG_FILE" <<EOF
# JIT SSH Agent Configuration
# Generated by install.sh on $(date)

# Control Plane URL (backend server)
control_plane_url = $CONTROL_PLANE_URL

# Agent Auth Token
agent_token = $AGENT_TOKEN

# Agent ID — auto-generated on first run, do not change
agent_id =

# Polling intervals (seconds)
heartbeat_interval_sec = $HEARTBEAT_INTERVAL
poll_interval_sec      = $POLL_INTERVAL

# Log output
log_file = $LOG_FILE

# Tags sent to control plane at registration
tags = $TAGS
EOF
  chmod 600 "$CONFIG_FILE"
  echo "[ok] Config written to $CONFIG_FILE"
fi

# ------- Install binary -------
if [ -n "$AGENT_BINARY_URL" ]; then
  echo "[info] Downloading agent binary from $AGENT_BINARY_URL ..."
  curl -fsSL -o "$BIN_PATH" "$AGENT_BINARY_URL"
  chmod +x "$BIN_PATH"
  echo "[ok] Binary installed to $BIN_PATH"
else
  # Try to find or build local binary
  SOURCE_BIN=""
  if [ -f "./jit-agent" ]; then
    SOURCE_BIN="./jit-agent"
  elif [ -f "./agent" ]; then
    SOURCE_BIN="./agent"
  elif [ -f "./bin/agent" ]; then
    SOURCE_BIN="./bin/agent"
  elif command -v go &>/dev/null; then
    echo "[info] Binary missing, but 'go' found. Building 'jit-agent'..."
    go build -o jit-agent . || echo "[error] Go build failed."
    [ -f "./jit-agent" ] && SOURCE_BIN="./jit-agent"
  fi

  if [ -n "$SOURCE_BIN" ]; then
    cp "$SOURCE_BIN" "$BIN_PATH"
    chmod +x "$BIN_PATH"
    echo "[ok] Binary $SOURCE_BIN copied to $BIN_PATH"
  else
    echo "ERROR: No jit-agent binary found at ./jit-agent or ./agent, and couldn't build it." >&2
    echo "Please build the agent first (go build -o jit-agent) or provide --binary-url." >&2
    exit 1
  fi
fi

# ------- Create systemd service -------
if command -v systemctl &>/dev/null; then
  cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=JIT SSH Access Agent
Documentation=https://github.com/manishjangra/jit-ssh-system
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$BIN_PATH $CONFIG_FILE
Restart=on-failure
RestartSec=10
StandardOutput=append:$LOG_FILE
StandardError=append:$LOG_FILE
User=root
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$CONFIG_DIR $LOG_FILE

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable jit-agent
  systemctl restart jit-agent
  echo "[ok] systemd service installed and started."
  echo ""
  echo "  View logs : journalctl -u jit-agent -f"
  echo "  Status    : systemctl status jit-agent"
else
  echo "[info] systemd not found. Start the agent manually:"
  echo "  $BIN_PATH $CONFIG_FILE"
fi

echo ""
echo "=== Installation Complete ==="
echo "  Config  : $CONFIG_FILE"
echo "  Binary  : $BIN_PATH"
echo "  Control : $CONTROL_PLANE_URL"
echo ""
echo "The agent will connect to the JIT control plane and appear in the"
echo "Servers list in the admin dashboard within 30 seconds."
